name: Build with pdflatex
on: [push, pull_request, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile paper-conference.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: paper-conference.tex
          compiler: pdflatex
          args:
      - name: Compile paper-conference-minted.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: paper-conference-minted.tex
          compiler: pdflatex
          args: -shell-escape
      - name: Compile paper-conference-compsoc.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: paper-conference-compsoc.tex
          compiler: pdflatex
          args:
      - name: Compile paper-9pt-technote.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: paper-9pt-technote.tex
          compiler: pdflatex
          args:
      - name: Gather build artifacts
        run: mkdir build && cp -r paper-*.pdf build/
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: pdflatex
          path: build/
          retention-days: 5
