name: Build and publish to gh-pages
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile paper-conference.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: paper-conference.tex
          args:
      - name: Compile paper-conference-minted.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: paper-conference-minted.tex
          args:
      - name: Compile paper-conference-compsoc.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: paper-conference-compsoc.tex
          args:
      - name: Compile paper-9pt-technote.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: paper-9pt-technote.tex
          args:
      - name: Gather build artifacts
        run: mkdir build && cp -r README.md paper-*.pdf .github/_config.yml build/
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
